"""initial backoffice schema

Revision ID: 0001
Revises:
Create Date: 2026-07-08 19:46:39.966957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from kavalai.db import uuid_column


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", uuid_column(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("db_host", sa.TEXT(), nullable=True),
        sa.Column("db_port", sa.Integer(), nullable=True),
        sa.Column("db_user", sa.TEXT(), nullable=True),
        sa.Column("db_password", sa.TEXT(), nullable=True),
        sa.Column("db_name", sa.TEXT(), nullable=True),
        sa.Column("db_schema", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_cache",
        sa.Column("id", uuid_column(), nullable=False),
        sa.Column("project_id", uuid_column(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("value", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project_cache", schema=None) as batch_op:
        batch_op.create_index("idx_project_cache_name", ["name"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", uuid_column(), nullable=False),
        sa.Column("email", sa.TEXT(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("picture", sa.TEXT(), nullable=True),
        sa.Column("active_project_id", uuid_column(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["active_project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "project_memberships",
        sa.Column("user_id", uuid_column(), nullable=False),
        sa.Column("project_id", uuid_column(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "viewer", name="project_role", native_enum=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "project_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_memberships")
    op.drop_table("users")
    with op.batch_alter_table("project_cache", schema=None) as batch_op:
        batch_op.drop_index("idx_project_cache_name")

    op.drop_table("project_cache")
    op.drop_table("projects")
    # ### end Alembic commands ###
